server:
  port: 8080
spring:
  config:
    import:
      - classpath:/application-db.yml
---
spring:
  config:
    activate:
      on-profile: local
---
spring:
  config:
    activate:
      on-profile: dev
---
spring:
  config:
    activate:
      on-profile: prod